all: mymaketestapp2

# Which compiler
CC = gcc

# Where are include files kept
INCLUDE = .

# Options for development
CFLAGS = -g -Wall -ansi

# Options for release
# CFLAGS = -O -Wall -ansi


mymaketestapp2: main.o p2.o p3.o
	$(CC) -o mymaketestapp2 main.o p2.o p3.o

main.o: main.c a.h
	$(CC) -I$(INCLUDE) $(CFLAGS) -c main.c

p2.o: p2.c a.h b.h
	$(CC) -I$(INCLUDE) $(CFLAGS) -c p2.c

p3.o: p3.c b.h c.h
	$(CC) -I$(INCLUDE) $(CFLAGS) -c p3.c

clean:
	-rm main.o p2.o p3.o


